kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: gitops-multi-002
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 8082
        protocol: TCP
  - role: worker
